sudo: required
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.6"
language: python
python:
  - "3.7"
install:
  - sudo apt-get install -y librrd-dev
  - pip install python-dateutil
  - pip install backports.weakref
  - pip install backports-datetime-fromisoformat
  - pip install pycodestyle
  - pip install coverage
  - pip install -r requirements.txt
before_script:
  - psql --version
  - psql -U postgres -c 'SELECT version();'
script:
  - ./scripts/test.sh
