sudo: required
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.6"
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install pycodestyle
  - pip install coverage
before_script:
  - psql --version
  - psql -U postgres -c 'SELECT version();'
script:
  - ./testing/test.sh
