# Generated by Django 4.0.4 on 2023-02-07 17:01

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0153_created_datetimefield'),
        ('tenancy', '0007_contact_link'),
        ('extras', '0073_journalentry_tags_custom_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Accounting Profile',
                'verbose_name_plural': 'Accounting Profiles',
                'ordering': ['member', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccountingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Accounting Source',
                'verbose_name_plural': 'Accounting Sources',
                'ordering': ['device', 'name', 'destination'],
            },
        ),
        migrations.CreateModel(
            name='LogicalSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Logical System',
                'verbose_name_plural': 'Logical Systems',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=255)),
                ('legacy_id', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('accounting_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sidekick.accountingprofile')),
                ('backup_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sidekick.networkservice')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('member_site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dcim.site')),
            ],
            options={
                'verbose_name': 'Network Service',
                'verbose_name_plural': 'Network Services',
                'ordering': ['member', 'network_service_type'],
            },
        ),
        migrations.CreateModel(
            name='NetworkServiceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('interface', models.CharField(blank=True, max_length=255, null=True)),
                ('vlan', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('legacy_id', models.CharField(blank=True, default='', max_length=255)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_service_devices', to='dcim.device')),
                ('network_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_service_devices', to='sidekick.networkservice')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Network Service Device',
                'verbose_name_plural': 'Network Service Devices',
            },
        ),
        migrations.CreateModel(
            name='RoutingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Routing Type',
                'verbose_name_plural': 'Routing Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('admin_status', models.IntegerField(default=True)),
                ('oper_status', models.IntegerField(default=True)),
                ('out_rate', models.BigIntegerField(default=0)),
                ('in_rate', models.BigIntegerField(default=0)),
                ('out_octets', models.BigIntegerField(default=0)),
                ('in_octets', models.BigIntegerField(default=0)),
                ('out_unicast_packets', models.BigIntegerField(default=0)),
                ('in_unicast_packets', models.BigIntegerField(default=0)),
                ('out_nunicast_packets', models.BigIntegerField(default=0)),
                ('in_nunicast_packets', models.BigIntegerField(default=0)),
                ('out_errors', models.BigIntegerField(default=0)),
                ('in_errors', models.BigIntegerField(default=0)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nic', to='dcim.interface')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'NIC',
                'verbose_name_plural': 'NICs',
                'ordering': ['interface__device__name', 'interface__name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Network Service Type',
                'verbose_name_plural': 'Network Service Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkServiceL2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('vlan', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('legacy_id', models.CharField(blank=True, default='', max_length=255)),
                ('network_service_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_service_l2', to='sidekick.networkservicedevice')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Network Service L2',
                'verbose_name_plural': 'Network Services L2',
            },
        ),
        migrations.CreateModel(
            name='NetworkServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('network_services', models.ManyToManyField(to='sidekick.networkservice')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Network Service Group',
                'verbose_name_plural': 'Network Service Groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='networkservice',
            name='network_service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='network_service_type', to='sidekick.networkservicetype'),
        ),
        migrations.AddField(
            model_name='networkservice',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='BandwidthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('effective_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('traffic_cap', models.BigIntegerField(blank=True, null=True)),
                ('burst_limit', models.BigIntegerField(blank=True, null=True)),
                ('accounting_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sidekick.accountingprofile')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Bandwidth Profile',
                'verbose_name_plural': 'Bandwidth Profiles',
                'ordering': ['accounting_profile'],
            },
        ),
        migrations.CreateModel(
            name='AccountingSourceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('scu', models.BigIntegerField(default=0)),
                ('dcu', models.BigIntegerField(default=0)),
                ('accounting_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sidekick.accountingsource')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Accounting Source Counter',
                'verbose_name_plural': 'Accounting Source Counters',
            },
        ),
        migrations.AddField(
            model_name='accountingprofile',
            name='accounting_sources',
            field=models.ManyToManyField(blank=True, to='sidekick.accountingsource'),
        ),
        migrations.AddField(
            model_name='accountingprofile',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='accountingprofile',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='NetworkServiceL3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('asn', models.CharField(blank=True, default='', max_length=255)),
                ('ipv4_unicast', models.BooleanField(default=True)),
                ('ipv4_multicast', models.BooleanField(default=True)),
                ('ipv4_prefixes', models.TextField(blank=True, null=True)),
                ('provider_router_address_ipv4', models.CharField(blank=True, default='', max_length=255)),
                ('member_router_address_ipv4', models.CharField(blank=True, default='', max_length=255)),
                ('ipv6_unicast', models.BooleanField(default=False)),
                ('ipv6_multicast', models.BooleanField(default=False)),
                ('ipv6_prefixes', models.TextField(blank=True, null=True)),
                ('provider_router_address_ipv6', models.CharField(blank=True, default='', max_length=255)),
                ('member_router_address_ipv6', models.CharField(blank=True, default='', max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('legacy_id', models.CharField(blank=True, default='', max_length=255)),
                ('logical_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_service_l3', to='sidekick.logicalsystem')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
                ('member_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dcim.site')),
                ('network_service_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_service_l3', to='sidekick.networkservicedevice')),
                ('routing_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='network_service_l3', to='sidekick.routingtype')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='extras.TaggedItem', to='extras.Tag', verbose_name='Tags')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Network Service L3',
                'verbose_name_plural': 'Network Services L3',
            },
        ),
    ]
