# Generated by Django 4.0.4 on 2025-05-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0057_created_datetimefield'),
        ('sidekick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkservicel3',
            name='ip_prefixes',
            field=models.ManyToManyField(blank=True, to='ipam.prefix'),
        ),
    ]
