# Generated by Django 6.1 on 2026-10-01 22:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidekick', '0002_alter_accountingprofile_custom_field_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandwidthprofile',
            name='effective_date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate, null=True),
        ),
    ]
